	var nombres = {	// 2: [
	// [0,1,0,0,0,1],
	// [1,0,0,0,1,1],
	// [1,0,0,1,0,1],
	// [1,0,1,0,0,1],
	// [0,1,0,0,0,1]],
	2 : [
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, true, true, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, true, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					true, true, true, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, true, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					true, false, true, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, true, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, true,
					true, false, true, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, true, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, true,
					false, false, true, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, true, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, true, true,
					false, false, true, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, true, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, true, true, false,
					false, false, true, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, true, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, true, false, false,
					false, false, true, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, true, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, true, true, false, false,
					false, false, true, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, true, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, true, false, false, false,
					false, false, true, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, true, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, true, false, false, false, false,
					false, false, true, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, true, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, true, false, false, false, false,
					false, false, true, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, true, true, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, true, false, false, false, false, false,
					false, false, true, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, true, true, false, false, false,
					false, false, false, false, false, false, false, false,
					false, true, false, false, false, false, false, false,
					false, false, true, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, true, true, false, false,
					false, false, false, false, false, false, false, false,
					true, false, false, false, false, false, false, false,
					false, false, true, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, true, true, true, false,
					false, false, false, false, false, false, true, false,
					false, false, false, false, false, false, false, false,
					false, true, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, true,
					true, true, true, true, true, true, true, false, false,
					false, false, false, false, false, false, false, false,
					false, true, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ] ],
	// 0: [
	// [0,1,1,1,1,0],
	// [1,0,0,0,0,1],
	// [1,0,0,0,0,1],
	// [1,0,0,0,0,1],
	// [0,1,1,1,1,0]],
	0 : [
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, true, true,
					true, true, true, true, true, true, true, true, true, true,
					true, true, true, true, true, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false ],
			[ false, false, false, false, false, false, false, true, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, true, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, true, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, true, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, true, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, true, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, true, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, true, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, true, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, true, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, true, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, true, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, true, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, true, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, true, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, true, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, true, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, true, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, true, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, true, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, true, true,
					true, true, true, true, true, true, true, true, true, true,
					true, true, true, true, true, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ] ],
	// 1: [
	// [0,0,0,0,0,0],
	// [0,1,0,0,0,1],
	// [1,1,1,1,1,1],
	// [0,0,0,0,0,1],
	// [0,0,0,0,0,0]],
	1 : [
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, true, false, false, false, false, false, false,
					false, false, false, false, true, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					true, false, false, false, false, false, false, false,
					false, false, false, false, true, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, true,
					false, false, false, false, false, false, false, false,
					false, false, false, false, true, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, true, true,
					true, true, true, true, true, true, true, true, true, true,
					true, true, true, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, true, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, true, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, true, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ] ],
	// 4: [
	// [0,0,1,1,0,0],
	// [0,1,0,1,0,0],
	// [1,0,0,1,0,0],
	// [1,1,1,1,1,1],
	// [0,0,0,0,0,0]],
	5 : [
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, true, true, true, true,
					true, true, true, true, true, true, true, true, true, true,
					true, false, false, false, false, false, false, false,
					false, false, false, false, true, false, false, false,
					false, false, false, false ],
			[ false, false, false, false, false, false, true, false, false,
					false, false, false, false, false, false, false, false,
					false, false, true, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					true, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, true, false, false,
					false, false, false, false, false, false, false, false,
					false, true, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, true, false, false, false, false, false ],
			[ false, false, false, false, false, false, true, false, false,
					false, false, false, false, false, false, false, false,
					false, true, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, true, false, false, false, false, false ],
			[ false, false, false, false, false, false, true, false, false,
					false, false, false, false, false, false, false, false,
					false, true, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, true, false, false, false, false, false ],
			[ false, false, false, false, false, false, true, false, false,
					false, false, false, false, false, false, false, false,
					false, true, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, true, false, false, false, false, false ],
			[ false, false, false, false, false, false, true, false, false,
					false, false, false, false, false, false, false, false,
					false, true, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, true, false, false, false, false, false ],
			[ false, false, false, false, false, false, true, false, false,
					false, false, false, false, false, false, false, false,
					false, true, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, true, false, false, false, false, false ],
			[ false, false, false, false, false, false, true, false, false,
					false, false, false, false, false, false, false, false,
					false, true, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, true, false, false, false, false, false ],
			[ false, false, false, false, false, false, true, false, false,
					false, false, false, false, false, false, false, false,
					false, true, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, true, false, false, false, false, false ],
			[ false, false, false, false, false, false, true, false, false,
					false, false, false, false, false, false, false, false,
					false, true, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, true, false, false, false, false, false ],
			[ false, false, false, false, false, false, true, false, false,
					false, false, false, false, false, false, false, false,
					false, true, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, true, false, false, false, false, false ],
			[ false, false, false, false, false, false, true, false, false,
					false, false, false, false, false, false, false, false,
					false, false, true, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					true, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, true, false, false, false, false,
					false, false, false, false, false, false, false, true,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, true, false, false, false,
					false, false, false, false, false, false, true, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, true, false, false,
					false, false, false, false, false, true, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, true, true, true,
					true, true, true, true, false, false, false, false, false,
					false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ] ],
	// 5: [
	// [1,1,1,0,0,1],
	// [1,0,1,0,0,1],
	// [1,0,1,0,0,1],
	// [1,0,1,0,0,1],
	// [1,0,0,1,1,0]],
	4 : [
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, true, true, true, true, true, true, true,
					true, true, true, true, true, true, true, true, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					true, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					true, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					true, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					true, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					true, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					true, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					true, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					true, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					true, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					true, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					true, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, true, true, true, true, true, true, true,
					true, true, true, true, true, true, true, true, true, true,
					true, true, true, true, true, true, true, true, true, true,
					false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ] ],
	// 3: [
	// [0,0,0,0,0,0],
	// [1,0,1,0,1,0],
	// [1,0,1,0,1,0],
	// [1,0,1,0,1,0],
	// [1,1,1,1,1,0]],
	3 : [
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, true, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, true, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, true, false, false, false ],
			[ false, false, false, false, false, false, true, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, true, false, false ],
			[ false, false, false, false, false, false, true, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, true, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, true, false, false ],
			[ false, false, false, false, false, false, true, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, true, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, true, false, false ],
			[ false, false, false, false, false, false, true, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, true, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, true, false, false ],
			[ false, false, false, false, false, false, true, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, true, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, true, false, false ],
			[ false, false, false, false, false, false, true, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, true, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, true, false, false ],
			[ false, false, false, false, false, false, false, true, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, true, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, true, false, false, false ],
			[ false, false, false, false, false, false, false, false, true,
					false, false, false, false, false, false, false, false,
					false, false, false, false, true, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, true, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					true, false, false, false, false, false, false, false,
					false, false, false, true, false, true, false, false,
					false, false, false, false, false, false, false, false,
					false, false, true, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, true, true, false, false, false, false, false,
					false, false, false, true, false, false, true, false,
					false, false, false, false, false, false, false, false,
					false, true, true, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, true, true, true, false, false, false,
					true, true, false, false, false, false, true, true, true,
					false, false, false, false, false, false, true, false,
					false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, true, true, true,
					false, false, false, false, false, false, false, false,
					false, true, true, true, true, true, true, false, false,
					false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ],
			[ false, false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false, false,
					false, false, false, false, false, false, false ] ],
};